/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this OnEnter
void main()
{

object oPC = GetEnteringObject();

if (!GetIsPC(oPC)) return;

if (GetItemPossessedBy(oPC, "ActivationStone")== OBJECT_INVALID)
   return;

FloatingTextStringOnCreature("The Portal doesn't seem to be working... perhaps you should speak with the priestess?", oPC);

}
